name: maven
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: self-hosted

    steps:
     - name: collecting the src code
       uses: actions/checkout@v7.0.0
       
     - name: installing the java 
       uses: actions/setup-java@v5.5.0
       with:
         java-version: '21'
         distribution: 'temurin'
         
     - name: generating packages
       shell: cmd
       run: mvn package


       
